### ISSUE TITLE
Ping error - operation cost

### ISSUE THREAD

**Issue by MikhailRadusha** [near/stakewars-iii#85]
Ping does not go through with error of not enough balance though I have balance on my account 
```
near call stingray.factory.shardnet.near ping '{}' --accountId stingray.shardnet.near --gas=300000000000000
Scheduling a call: stingray.factory.shardnet.near.ping({})
Doing account.functionCall()
ServerError: Sender stingray.shardnet.near does not have enough balance 26.026831465460946155827066 for operation costing 37.854480396494967545665848
    at Object.parseRpcError (/usr/lib/node_modules/near-cli/node_modules/near-api-js/lib/utils/rpc_errors.js:24:19)
    at /usr/lib/node_modules/near-cli/node_modules/near-api-js/lib/providers/json-rpc-provider.js:319:44
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.exponentialBackoff [as default] (/usr/lib/node_modules/near-cli/node_modules/near-api-js/lib/utils/exponential-backoff.js:7:24)
    at async JsonRpcProvider.sendJsonRpc (/usr/lib/node_modules/near-cli/node_modules/near-api-js/lib/providers/json-rpc-provider.js:304:26)
    at async /usr/lib/node_modules/near-cli/node_modules/near-api-js/lib/account.js:121:24
    at async Object.exponentialBackoff [as default] (/usr/lib/node_modules/near-cli/node_modules/near-api-js/lib/utils/exponential-backoff.js:7:24)
    at async Account.signAndSendTransactionV2 (/usr/lib/node_modules/near-cli/node_modules/near-api-js/lib/account.js:117:24)
    at async scheduleFunctionCall (/usr/lib/node_modules/near-cli/commands/call.js:57:38)
    at async Object.handler (/usr/lib/node_modules/near-cli/utils/exit-on-error.js:52:9) {
  type: 'NotEnoughBalance',
  context: ErrorContext {
    transactionHash: 'BNiXN3vgcVAHzSBW3mEAukuEHrEF4efYm7FiSwJmNc5r'
  },
  balance: '26026831465460946155827066',
  cost: '37854480396494967545665848',
  signer_id: 'stingray.shardnet.near',
  kind: {
    balance: '26026831465460946155827066',
    cost: '37854480396494967545665848',
    signer_id: 'stingray.shardnet.near'
  }
}
```
![image](https://user-images.githubusercontent.com/87991370/183043636-f0c6a6ab-3b00-41e4-876c-477932977847.png)

**Comment by Huagiang** [comment]
me too

**Comment by joesixpack** [comment]
Same here.

**Comment by DDeAlmeida** [comment]
Ping cost is now fixed
Closing
