### ISSUE TITLE
Minimum Storage Cost Continuously Increasing

### ISSUE THREAD

**Issue by joesixpack** [near/stakewars-iii#88]
```
j@vulpecula:~$ ./near-withdrawall.sh
Scheduling a call: ou8122.factory.shardnet.near.withdraw_all()
Doing account.functionCall()
ServerError: The account  wouldn't have enough balance to cover storage, required to have 1343917603077231960294090 yoctoNEAR more
    at Object.parseRpcError (/home/j/.npm-global/lib/node_modules/near-cli/node_modules/near-api-js/lib/utils/rpc_errors.js:24:19)
    at /home/j/.npm-global/lib/node_modules/near-cli/node_modules/near-api-js/lib/providers/json-rpc-provider.js:319:44
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.exponentialBackoff [as default] (/home/j/.npm-global/lib/node_modules/near-cli/node_modules/near-api-js/lib/utils/exponential-backoff.js:7:24)
    at async JsonRpcProvider.sendJsonRpc (/home/j/.npm-global/lib/node_modules/near-cli/node_modules/near-api-js/lib/providers/json-rpc-provider.js:304:26)
    at async /home/j/.npm-global/lib/node_modules/near-cli/node_modules/near-api-js/lib/account.js:121:24
    at async Object.exponentialBackoff [as default] (/home/j/.npm-global/lib/node_modules/near-cli/node_modules/near-api-js/lib/utils/exponential-backoff.js:7:24)
    at async Account.signAndSendTransactionV2 (/home/j/.npm-global/lib/node_modules/near-cli/node_modules/near-api-js/lib/account.js:117:24)
    at async scheduleFunctionCall (/home/j/.npm-global/lib/node_modules/near-cli/commands/call.js:57:38)
    at async Object.handler (/home/j/.npm-global/lib/node_modules/near-cli/utils/exit-on-error.js:52:9) {
  type: 'LackBalanceForState',
  context: ErrorContext {
    transactionHash: 'Fg7EiQ6DLhd3WjgiUsghha7mpjAhKNbEcFUDr1WwsyLE'
  },
  account_id: undefined,
  amount: '1343917603077231960294090',
  kind: {
    amount: '1343917603077231960294090',
    signer_id: 'ou812.shardnet.near'
  }
}

```

Half an hour later:

```
./near-withdrawall.sh
Scheduling a call: ou8122.factory.shardnet.near.withdraw_all()
Doing account.functionCall()
ServerError: The account  wouldn't have enough balance to cover storage, required to have 1664538455687186599190127 yoctoNEAR more
    at Object.parseRpcError (/home/j/.npm-global/lib/node_modules/near-cli/node_modules/near-api-js/lib/utils/rpc_errors.js:24:19)
    at /home/j/.npm-global/lib/node_modules/near-cli/node_modules/near-api-js/lib/providers/json-rpc-provider.js:319:44
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.exponentialBackoff [as default] (/home/j/.npm-global/lib/node_modules/near-cli/node_modules/near-api-js/lib/utils/exponential-backoff.js:7:24)
    at async JsonRpcProvider.sendJsonRpc (/home/j/.npm-global/lib/node_modules/near-cli/node_modules/near-api-js/lib/providers/json-rpc-provider.js:304:26)
    at async /home/j/.npm-global/lib/node_modules/near-cli/node_modules/near-api-js/lib/account.js:121:24
    at async Object.exponentialBackoff [as default] (/home/j/.npm-global/lib/node_modules/near-cli/node_modules/near-api-js/lib/utils/exponential-backoff.js:7:24)
    at async Account.signAndSendTransactionV2 (/home/j/.npm-global/lib/node_modules/near-cli/node_modules/near-api-js/lib/account.js:117:24)
    at async scheduleFunctionCall (/home/j/.npm-global/lib/node_modules/near-cli/commands/call.js:57:38)
    at async Object.handler (/home/j/.npm-global/lib/node_modules/near-cli/utils/exit-on-error.js:52:9) {
  type: 'LackBalanceForState',
  context: ErrorContext {
    transactionHash: '7GYcwGJUsUZckwywZjtRR2vLvYkXsctrFJjqFxnD6ABj'
  },
  account_id: undefined,
  amount: '1664538455687186599190127',
  kind: {
    amount: '1664538455687186599190127',
    signer_id: 'ou812.shardnet.near'
  }
}
```

**Comment by ivanguardia** [comment]
You need a minium balance in your wallet to be able of invoking contracts.

**Comment by joesixpack** [comment]
In hindsight it was related to the gas being too high.
