### ISSUE TITLE
Cannot destructure property 'result' of 'response' as it is null.

### ISSUE THREAD

**Issue by joesixpack** [near/stakewars-iii#89]
Retrying request to broadcast_tx_commit as it has timed out [
  'EwAAAG91ODEyLnNoYXJkbmV0Lm5lYXIAHAteLkoudr+9X/Y3TAKlZ3V18HADs1yYjNPvUTBVFRaIlSec0QAAABwAAABvdTgxMjIuZmFjdG9yeS5zaGFyZG5ldC5uZWFyo0/Vb+fao5IVU6G0Y2SaT6ZRJ/AGZDdb2TdbXAnwEpQBAAAAAgQAAABwaW5nAgAAAHt9ADDvfboCAAAAAAAAAAAAAAAAAAAAAAAAANot4Obs8ZPaItQCgzn136WD3x8dVaAnWWx4X7vJJVzckTtyMSZne12JJGpvHCTKto5Bcwk1mQXI8Fk7m/sQXAo='
]
TypeError: Cannot destructure property 'result' of 'response' as it is null.
    at JsonRpcProvider.sendJsonRpc (/home/j/.npm-global/lib/node_modules/near-cli/node_modules/near-api-js/lib/providers/json-rpc-provider.js:345:17)
    at async /home/j/.npm-global/lib/node_modules/near-cli/node_modules/near-api-js/lib/account.js:121:24
    at async Object.exponentialBackoff [as default] (/home/j/.npm-global/lib/node_modules/near-cli/node_modules/near-api-js/lib/utils/exponential-backoff.js:7:24)
    at async Account.signAndSendTransactionV2 (/home/j/.npm-global/lib/node_modules/near-cli/node_modules/near-api-js/lib/account.js:117:24)
    at async scheduleFunctionCall (/home/j/.npm-global/lib/node_modules/near-cli/commands/call.js:57:38)
    at async Object.handler (/home/j/.npm-global/lib/node_modules/near-cli/utils/exit-on-error.js:52:9) {
  context: ErrorContext {
    transactionHash: '7w6EutK1a6gYQGR3ff42dCWmsLjFuVomw6TWHT8aTGZ7'
  }
}

**Comment by ivanguardia** [comment]
![image](https://user-images.githubusercontent.com/101866292/183706579-0c98d5fe-f5a2-439e-aebe-be842f680eb8.png)
The same isu from wallet.
